name: grid_tracfin_project

services:
  # my-keycloak:
  #   image: quay.io/keycloak/keycloak:26.0.5
  #   environment:
  #     KC_HOSTNAME: localhost
  #     KC_HOSTNAME_PORT: 7080
  #     KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #     KC_HEALTH_ENABLED: "true"
  #     KC_LOG_LEVEL: info
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
  #     interval: 15s
  #     timeout: 2s
  #     retries: 15
  #   command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
  #   ports:
  #     - "7080:7080"
  #     - "7443:7443"
  #   networks:
  #     - local_network

  postgres:
    image: postgres:1.17@sha256:163763c8afd28cae69035ce84b12d8180179559c747c0701b3cad17818a0dbc5
    restart: always
    container_name: database
    env_file:
      - ../env/postgres/postgres.env
    ports:
      - 5432:5432

  python-server:
    build: 
      context: .
      dockerfile: dockerfile/grid_tracfin_python/Dockerfile
    container_name: python-server
    ports:
      - 8080:8080
    depends_on:
      - postgres
    tty: true

  #postgres_keycloak:
  #  image: postgres:dev
 #  container_name: database_keycloak
  #  volume:
  #    - postgres_keycloak_version_1:/var/lib/postgresql/data/pgdata
  #  env_file:
  #    - ./env/postgres_keycloak.env
  #  ports:
  #    - 5433:5433
  #  deploy:
  #    resources:
  #      limits:
  #        cpus: '0.50'
      
networks:
  local_network:
    driver: bridge
